apiVersion: v1
kind: Pod
metadata:
  name: matchmaker
  namespace: emortalmc
  labels:
    app: matchmaker

spec:
  containers:
    - name: matchmaker
      image: emortalmc/kurushimi:dev
      imagePullPolicy: Never
      ports:
        - name: grpc
          containerPort: 8080
          hostPort: 8080

      env:
        - name: TRACKER_ENABLED
          value: "true"
        - name: KURUSHIMI_REDIS_HOST # Well this is horrible but Viper says we have to use a `.` to separate nested keys
          value: "redis-master"
        - name: KURUSHIMI_NAMESPACE
          value: "emortalmc"
        - name: KURUSHIMI_RABBITMQ_HOST
          value: "host.minikube.internal"

  serviceAccountName: matchmaker
  automountServiceAccountToken: true

---
#apiVersion: v1
#kind: Service
#metadata:
#  name: matchmaker
#  namespace: emortalmc
#  annotations:
#    linkerd.io/inject: enabled
#
#spec:
#  type: ClusterIP
#  ports:
#    - name: grpc
#      port: 9090
#      targetPort: 9090
#
#  selector:
#    app: matchmaker
