apiVersion: v1
kind: Service

metadata:
  name: matchmaker
  namespace: emortalmc

spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9010
      targetPort: 9010

  selector:
    app: matchmaker
