// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: messages.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TicketDeletedMessage_Reason int32

const (
	TicketDeletedMessage_GAME_MODE_DELETED TicketDeletedMessage_Reason = 0
	TicketDeletedMessage_MANUAL_DEQUEUE    TicketDeletedMessage_Reason = 1
	TicketDeletedMessage_MATCH_CREATED     TicketDeletedMessage_Reason = 2
)

// Enum value maps for TicketDeletedMessage_Reason.
var (
	TicketDeletedMessage_Reason_name = map[int32]string{
		0: "GAME_MODE_DELETED",
		1: "MANUAL_DEQUEUE",
		2: "MATCH_CREATED",
	}
	TicketDeletedMessage_Reason_value = map[string]int32{
		"GAME_MODE_DELETED": 0,
		"MANUAL_DEQUEUE":    1,
		"MATCH_CREATED":     2,
	}
)

func (x TicketDeletedMessage_Reason) Enum() *TicketDeletedMessage_Reason {
	p := new(TicketDeletedMessage_Reason)
	*p = x
	return p
}

func (x TicketDeletedMessage_Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TicketDeletedMessage_Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (TicketDeletedMessage_Reason) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x TicketDeletedMessage_Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TicketDeletedMessage_Reason.Descriptor instead.
func (TicketDeletedMessage_Reason) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2, 0}
}

type PendingMatchDeletedMessage_Reason int32

const (
	PendingMatchDeletedMessage_CANCELLED     PendingMatchDeletedMessage_Reason = 0
	PendingMatchDeletedMessage_MATCH_CREATED PendingMatchDeletedMessage_Reason = 1
)

// Enum value maps for PendingMatchDeletedMessage_Reason.
var (
	PendingMatchDeletedMessage_Reason_name = map[int32]string{
		0: "CANCELLED",
		1: "MATCH_CREATED",
	}
	PendingMatchDeletedMessage_Reason_value = map[string]int32{
		"CANCELLED":     0,
		"MATCH_CREATED": 1,
	}
)

func (x PendingMatchDeletedMessage_Reason) Enum() *PendingMatchDeletedMessage_Reason {
	p := new(PendingMatchDeletedMessage_Reason)
	*p = x
	return p
}

func (x PendingMatchDeletedMessage_Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PendingMatchDeletedMessage_Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[1].Descriptor()
}

func (PendingMatchDeletedMessage_Reason) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[1]
}

func (x PendingMatchDeletedMessage_Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PendingMatchDeletedMessage_Reason.Descriptor instead.
func (PendingMatchDeletedMessage_Reason) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5, 0}
}

type TicketCreatedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ticket *Ticket `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
}

func (x *TicketCreatedMessage) Reset() {
	*x = TicketCreatedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketCreatedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketCreatedMessage) ProtoMessage() {}

func (x *TicketCreatedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketCreatedMessage.ProtoReflect.Descriptor instead.
func (*TicketCreatedMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *TicketCreatedMessage) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

type TicketUpdatedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewTicket *Ticket `protobuf:"bytes,1,opt,name=new_ticket,json=newTicket,proto3" json:"new_ticket,omitempty"`
}

func (x *TicketUpdatedMessage) Reset() {
	*x = TicketUpdatedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketUpdatedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketUpdatedMessage) ProtoMessage() {}

func (x *TicketUpdatedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketUpdatedMessage.ProtoReflect.Descriptor instead.
func (*TicketUpdatedMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *TicketUpdatedMessage) GetNewTicket() *Ticket {
	if x != nil {
		return x.NewTicket
	}
	return nil
}

// TicketDeletedMessage is sent when a ticket is deleted
// NOTE: This is not when a delete request is received, but when the removal gets processed.
// If this message is received, the ticket is no longer in any queue
// NOTE 2: This is not fired when a PendingMatch is converted to a Match. In that case, only a MatchCreatedMessage is sent.
type TicketDeletedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ticket *Ticket                     `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	Reason TicketDeletedMessage_Reason `protobuf:"varint,2,opt,name=reason,proto3,enum=emortal.kurushimi.messages.TicketDeletedMessage_Reason" json:"reason,omitempty"`
}

func (x *TicketDeletedMessage) Reset() {
	*x = TicketDeletedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TicketDeletedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketDeletedMessage) ProtoMessage() {}

func (x *TicketDeletedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketDeletedMessage.ProtoReflect.Descriptor instead.
func (*TicketDeletedMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *TicketDeletedMessage) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

func (x *TicketDeletedMessage) GetReason() TicketDeletedMessage_Reason {
	if x != nil {
		return x.Reason
	}
	return TicketDeletedMessage_GAME_MODE_DELETED
}

type PendingMatchCreatedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PendingMatch *PendingMatch `protobuf:"bytes,1,opt,name=pending_match,json=pendingMatch,proto3" json:"pending_match,omitempty"`
}

func (x *PendingMatchCreatedMessage) Reset() {
	*x = PendingMatchCreatedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PendingMatchCreatedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingMatchCreatedMessage) ProtoMessage() {}

func (x *PendingMatchCreatedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingMatchCreatedMessage.ProtoReflect.Descriptor instead.
func (*PendingMatchCreatedMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *PendingMatchCreatedMessage) GetPendingMatch() *PendingMatch {
	if x != nil {
		return x.PendingMatch
	}
	return nil
}

// PendingMatchUpdatedMessage is sent when players join/leave a pending match
// which can be used to update the UI with the player count
type PendingMatchUpdatedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PendingMatch *PendingMatch `protobuf:"bytes,1,opt,name=pending_match,json=pendingMatch,proto3" json:"pending_match,omitempty"`
}

func (x *PendingMatchUpdatedMessage) Reset() {
	*x = PendingMatchUpdatedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PendingMatchUpdatedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingMatchUpdatedMessage) ProtoMessage() {}

func (x *PendingMatchUpdatedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingMatchUpdatedMessage.ProtoReflect.Descriptor instead.
func (*PendingMatchUpdatedMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *PendingMatchUpdatedMessage) GetPendingMatch() *PendingMatch {
	if x != nil {
		return x.PendingMatch
	}
	return nil
}

type PendingMatchDeletedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PendingMatch *PendingMatch                     `protobuf:"bytes,1,opt,name=pending_match,json=pendingMatch,proto3" json:"pending_match,omitempty"`
	Reason       PendingMatchDeletedMessage_Reason `protobuf:"varint,2,opt,name=reason,proto3,enum=emortal.kurushimi.messages.PendingMatchDeletedMessage_Reason" json:"reason,omitempty"`
}

func (x *PendingMatchDeletedMessage) Reset() {
	*x = PendingMatchDeletedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PendingMatchDeletedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingMatchDeletedMessage) ProtoMessage() {}

func (x *PendingMatchDeletedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingMatchDeletedMessage.ProtoReflect.Descriptor instead.
func (*PendingMatchDeletedMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *PendingMatchDeletedMessage) GetPendingMatch() *PendingMatch {
	if x != nil {
		return x.PendingMatch
	}
	return nil
}

func (x *PendingMatchDeletedMessage) GetReason() PendingMatchDeletedMessage_Reason {
	if x != nil {
		return x.Reason
	}
	return PendingMatchDeletedMessage_CANCELLED
}

type MatchCreatedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Match *Match `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
}

func (x *MatchCreatedMessage) Reset() {
	*x = MatchCreatedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatchCreatedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCreatedMessage) ProtoMessage() {}

func (x *MatchCreatedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCreatedMessage.ProtoReflect.Descriptor instead.
func (*MatchCreatedMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *MatchCreatedMessage) GetMatch() *Match {
	if x != nil {
		return x.Match
	}
	return nil
}

var File_messages_proto protoreflect.FileDescriptor

var file_messages_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x1a, 0x65, 0x6d, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2e, 0x6b, 0x75, 0x72, 0x75, 0x73, 0x68,
	0x69, 0x6d, 0x69, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x0c, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x14, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x65, 0x6d, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2e, 0x6b, 0x75, 0x72,
	0x75, 0x73, 0x68, 0x69, 0x6d, 0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x52, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x56, 0x0a, 0x14, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x3e, 0x0a, 0x0a, 0x6e, 0x65, 0x77, 0x5f, 0x74, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x65, 0x6d, 0x6f, 0x72, 0x74, 0x61,
	0x6c, 0x2e, 0x6b, 0x75, 0x72, 0x75, 0x73, 0x68, 0x69, 0x6d, 0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x09, 0x6e, 0x65, 0x77, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x22, 0xe8, 0x01, 0x0a, 0x14, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x37, 0x0a, 0x06,
	0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x65,
	0x6d, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2e, 0x6b, 0x75, 0x72, 0x75, 0x73, 0x68, 0x69, 0x6d, 0x69,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06, 0x74,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x4f, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x37, 0x2e, 0x65, 0x6d, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2e,
	0x6b, 0x75, 0x72, 0x75, 0x73, 0x68, 0x69, 0x6d, 0x69, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x46, 0x0a, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x12, 0x15, 0x0a, 0x11, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x5f, 0x44, 0x45,
	0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x4d, 0x41, 0x4e, 0x55, 0x41,
	0x4c, 0x5f, 0x44, 0x45, 0x51, 0x55, 0x45, 0x55, 0x45, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x4d,
	0x41, 0x54, 0x43, 0x48, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x10, 0x02, 0x22, 0x68,
	0x0a, 0x1a, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x4a, 0x0a, 0x0d,
	0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x65, 0x6d, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2e, 0x6b, 0x75,
	0x72, 0x75, 0x73, 0x68, 0x69, 0x6d, 0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x65,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x0c, 0x70, 0x65, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x22, 0x68, 0x0a, 0x1a, 0x50, 0x65, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e,
	0x65, 0x6d, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2e, 0x6b, 0x75, 0x72, 0x75, 0x73, 0x68, 0x69, 0x6d,
	0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4d,
	0x61, 0x74, 0x63, 0x68, 0x52, 0x0c, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x74,
	0x63, 0x68, 0x22, 0xeb, 0x01, 0x0a, 0x1a, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4d, 0x61,
	0x74, 0x63, 0x68, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x65, 0x6d, 0x6f, 0x72, 0x74,
	0x61, 0x6c, 0x2e, 0x6b, 0x75, 0x72, 0x75, 0x73, 0x68, 0x69, 0x6d, 0x69, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x0c, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x55, 0x0a,
	0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3d, 0x2e,
	0x65, 0x6d, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2e, 0x6b, 0x75, 0x72, 0x75, 0x73, 0x68, 0x69, 0x6d,
	0x69, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x50, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x22, 0x2a, 0x0a, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x0d,
	0x0a, 0x09, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x4c, 0x45, 0x44, 0x10, 0x00, 0x12, 0x11, 0x0a,
	0x0d, 0x4d, 0x41, 0x54, 0x43, 0x48, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x10, 0x01,
	0x22, 0x4b, 0x0a, 0x13, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x34, 0x0a, 0x05, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x65, 0x6d, 0x6f, 0x72, 0x74, 0x61, 0x6c,
	0x2e, 0x6b, 0x75, 0x72, 0x75, 0x73, 0x68, 0x69, 0x6d, 0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x05, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x42, 0x4d, 0x0a,
	0x22, 0x64, 0x65, 0x76, 0x2e, 0x65, 0x6d, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x6b, 0x75, 0x72, 0x75, 0x73, 0x68, 0x69, 0x6d, 0x69, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x50, 0x01, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x65, 0x6d, 0x6f, 0x72, 0x74, 0x61, 0x6c, 0x6d, 0x63, 0x2f, 0x6b, 0x75, 0x72, 0x75,
	0x73, 0x68, 0x69, 0x6d, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData = file_messages_proto_rawDesc
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_proto_rawDescData)
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_messages_proto_goTypes = []interface{}{
	(TicketDeletedMessage_Reason)(0),       // 0: emortal.kurushimi.messages.TicketDeletedMessage.Reason
	(PendingMatchDeletedMessage_Reason)(0), // 1: emortal.kurushimi.messages.PendingMatchDeletedMessage.Reason
	(*TicketCreatedMessage)(nil),           // 2: emortal.kurushimi.messages.TicketCreatedMessage
	(*TicketUpdatedMessage)(nil),           // 3: emortal.kurushimi.messages.TicketUpdatedMessage
	(*TicketDeletedMessage)(nil),           // 4: emortal.kurushimi.messages.TicketDeletedMessage
	(*PendingMatchCreatedMessage)(nil),     // 5: emortal.kurushimi.messages.PendingMatchCreatedMessage
	(*PendingMatchUpdatedMessage)(nil),     // 6: emortal.kurushimi.messages.PendingMatchUpdatedMessage
	(*PendingMatchDeletedMessage)(nil),     // 7: emortal.kurushimi.messages.PendingMatchDeletedMessage
	(*MatchCreatedMessage)(nil),            // 8: emortal.kurushimi.messages.MatchCreatedMessage
	(*Ticket)(nil),                         // 9: emortal.kurushimi.model.Ticket
	(*PendingMatch)(nil),                   // 10: emortal.kurushimi.model.PendingMatch
	(*Match)(nil),                          // 11: emortal.kurushimi.model.Match
}
var file_messages_proto_depIdxs = []int32{
	9,  // 0: emortal.kurushimi.messages.TicketCreatedMessage.ticket:type_name -> emortal.kurushimi.model.Ticket
	9,  // 1: emortal.kurushimi.messages.TicketUpdatedMessage.new_ticket:type_name -> emortal.kurushimi.model.Ticket
	9,  // 2: emortal.kurushimi.messages.TicketDeletedMessage.ticket:type_name -> emortal.kurushimi.model.Ticket
	0,  // 3: emortal.kurushimi.messages.TicketDeletedMessage.reason:type_name -> emortal.kurushimi.messages.TicketDeletedMessage.Reason
	10, // 4: emortal.kurushimi.messages.PendingMatchCreatedMessage.pending_match:type_name -> emortal.kurushimi.model.PendingMatch
	10, // 5: emortal.kurushimi.messages.PendingMatchUpdatedMessage.pending_match:type_name -> emortal.kurushimi.model.PendingMatch
	10, // 6: emortal.kurushimi.messages.PendingMatchDeletedMessage.pending_match:type_name -> emortal.kurushimi.model.PendingMatch
	1,  // 7: emortal.kurushimi.messages.PendingMatchDeletedMessage.reason:type_name -> emortal.kurushimi.messages.PendingMatchDeletedMessage.Reason
	11, // 8: emortal.kurushimi.messages.MatchCreatedMessage.match:type_name -> emortal.kurushimi.model.Match
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	file_models_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketCreatedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketUpdatedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TicketDeletedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PendingMatchCreatedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PendingMatchUpdatedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PendingMatchDeletedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatchCreatedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_rawDesc = nil
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
