name: "Build and push"

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "emortalmc/actions/go/lint@main"

  publish:
    needs: "lint"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "emortalmc/actions/go/publish-single@main"
        with:
          registry-password: "${{ secrets.GITHUB_TOKEN }}"

  deploy:
    needs: "publish"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "emortalmc/actions/argo-sync@main"
        with:
          deployment-name: "matchmaker"
          values-path: "service/values/matchmaker.yaml"
          deployments-repo-token: "${{ secrets.DEPLOYMENTS_REPO_TOKEN }}"
